### ISSUE TITLE
[FEAT] Create an option to disable the API Server on Start

### ISSUE THREAD

**Issue by MaxBurn7** [Kruptein/PlanarAlly#722]
**Is your feature request related to a problem? Please describe.**
With my setup I am having problems starting up the API server and that is causing the whole container to fail.
[https://github.com/Kruptein/planarally-docs/issues/81](https://github.com/Kruptein/planarally-docs/issues/81)
```
planarally    | 2021-03-26 02:26:01,292 - WARNING -  RUNNING IN NON SSL CONTEXT  (planarserver.py:61)
planarally    | ======== Starting Webserver on http://0.0.0.0:8000/ ========
planarally    |
planarally    | 2021-03-26 02:26:01,293 - WARNING -  RUNNING IN NON SSL CONTEXT  (planarserver.py:61)
planarally    | Task exception was never retrieved
planarally    | future: <Task finished coro=<start_servers() done, defined at planarserver.py:119> exception=OSError(99, "error while attempting to bind on address ('::1', 8001, 0, 0): cannot assign requested address")>
planarally    | Traceback (most recent call last):
planarally    |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1073, in create_server
planarally    |     sock.bind(sa)
planarally    | OSError: [Errno 99] Cannot assign requested address
planarally    |
planarally    | During handling of the above exception, another exception occurred:
planarally    |
planarally    | Traceback (most recent call last):
planarally    |   File "planarserver.py", line 123, in start_servers
planarally    |     await start_server("APIserver")
planarally    |   File "planarserver.py", line 113, in start_server
planarally    |     await start_http(app, host, port)
planarally    |   File "planarserver.py", line 62, in start_http
planarally    |     await setup_runner(app, web.TCPSite, host=host, port=port)
planarally    |   File "/planarally/app.py", line 32, in setup_runner
planarally    |     await s.start()
planarally    |   File "/usr/local/lib/python3.6/site-packages/aiohttp/web_runner.py", line 128, in start
planarally    |     reuse_port=self._reuse_port,
planarally    |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1077, in create_server
planarally    |     % (sa, err.strerror.lower()))
planarally    | OSError: [Errno 99] error while attempting to bind on address ('::1', 8001, 0, 0): cannot assign requested address
```

**Describe the solution you'd like**
I would like an option to disable the the API server so Planar Ally can still be used while debugging the issues surrounding standing up the API server. Ideally it would probably be to have it enabled by default (as to not break existing user's compose files). Something like:
`- api-server=false`

**Describe alternatives you've considered**
An alternative solution would be to change it so that if the AIP server fails to start, the regular server continues to function. 

**Additional context**
I am using docker-compose and traefik. Below is an anonymized version of my compose file:
```
---
version: "3.7"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    restart: always
    command:
      - --log.level=WARN
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.cloudflare.acme.httpchallenge=true
      - --certificatesresolvers.cloudflare.acme.httpchallenge.entrypoint=web
      # - --certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.cloudflare.acme.email=email@domain.tdl
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  planarally:
    image: kruptein/planarally:latest
    container_name: planarally
    restart: unless-stopped
    volumes:
      - /mnt/unraid/docker/planarally/data:/planarally/data/
      - /mnt/unraid/docker/planarally/static/assets:/planarally/static/assets/
    labels:
      - traefik.http.services.pa.loadbalancer.server.scheme=https
      - traefik.http.services.pa.loadbalancer.server.port=8000
      - traefik.enable=true
      - traefik.http.routers.pa-http.service=pa
      - traefik.http.routers.pa-http.rule=Host(`pa.domain.tdl`)
      - traefik.http.routers.pa-http.entrypoints=web
      - traefik.http.routers.pa.service=pa
      - traefik.http.routers.pa.rule= Host(`pa.domain.tdl`)
      - traefik.http.routers.pa.entrypoints=websecure
      - traefik.http.routers.pa.tls=true
      - traefik.http.routers.pa.tls.certresolver=cloudflare
      - traefik.http.routers.pa.tls.domains[0].main=domain.tdl
      - traefik.http.routers.pa.tls.domains[0].sans=pa.domain.tdl
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      # these are required, this forces the websocket to forward over https
      - traefik.http.routers.pa.middlewares=ssl-header
      - traefik.http.middlewares.ssl-header.headers.customrequestheaders.X-Forwarded-Proto=https

# Included to show a working service. Going to "whoami.domain.tdl" produces the exspected results.
  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.domain.tdl`)
      - traefik.http.routers.whoami.entrypoints=websecure
      # Uses the Host rule to define which certificate to issue
      - traefik.http.routers.whoami.tls.certresolver=cloudflare
```
